language: elixir
elixir:
  - 1.7.0
  - 1.6.6
  - 1.6.5
  - 1.6.4
  - 1.6.3
  - 1.6.2
  - 1.6.1
  - 1.6.0
otp_release:
  - 21.0
  - 20.3
  - 20.1
  - 20.0
  - 19.3
  - 19.2
  - 19.1
  - 19.0
sudo: false
